### ISSUE TITLE
Yearly is not a valid period

### ISSUE THREAD

**Issue by LGGGreg** [custom-components/grocy#107]
Hi there, thanks so much for this component!

**Describe the bug**
I noticed today when I added a yearly chore, the sensor would only report unknown, and there was an error in the log saying that a yearly period was not valid.

**Expected behavior**
Sensor does not error and only show unknown state when a yearly chore exists

**To Reproduce**
1. Set up everything, see that everything works, sensor shows
1. Go to Grocy, add a new chore with a yearly period
2. See error bellow in log
3. See sensor as "Grocy chores - Unknown"
4. See ui component throw error from the sensor being unknown
5. Delete the yearly chore in gorcy
6. see functionality return
7. see grocy chore sensor as "3 Chore(s)" etc

**What is your installed versions of Home Assistant, Grocy and this integration?**
Home Assistant 0.116.4
Grocy version: 0.9.1
Integration 2.0.2

**How do you have Grocy installed? Add-on or external?**
Add-on

**Have you added debugging to the log, and what does the log say?**
Yes, the only interesting part is
2020-10-20 10:45:07 ERROR (MainThread) [custom_components.grocy] Update of Overdue_chores failed with 'yearly' is not a valid PeriodType
2020-10-20 10:45:07 ERROR (MainThread) [custom_components.grocy] Update of Chores failed with 'yearly' is not a valid PeriodType

**JSON service data (if related to using a service)**
na
```

**Extra info**
I don't know python, but maybe 'yearly' needs to be transformed to 'year'?

**Comment by mdallaire** [comment]
I am seeing the exact same issue with having a yearly chore. I was able to workaround the issue by changing it to a task that repeat every 12 months instead of yearly.

**Comment by GlennGoddard** [comment]
Unfortunately, I can not do the work around since I have some 10 year items and grocy limits months to 30 when I need 120.
I looked thru the code and I did not see anything in this integration concerning the periodicity; it appears to be Home Assistant does not accept yearly.

**Comment by isabellaalstrom** [comment]
I belive this is a problem coming from the lib. Here for chores: https://github.com/SebRut/pygrocy/blob/dea20ff696032c1d0a9b833a97dc74806beb7ffb/pygrocy/data_models/chore.py#L9

**Comment by GregHKI** [comment]
Dang that was fast, I was just about to make an issue, thank you!

**Comment by LGGGreg** [comment]
Dang that was fast, I was just about to make an issue, thank you!

**Comment by SebRut** [comment]
I guess you still need a new pygrocy release, right?

**Comment by isabellaalstrom** [comment]
Yes :)

**Comment by SebRut** [comment]
Should be fixed in 0.24.1 :)

**Comment by isabellaalstrom** [comment]
Please try pre-release v2.2.0b to see if this fixes the error.

**Comment by GlennGoddard** [comment]
The beta works for displaying chores yearly or greater now.

For a 10 year example:
The period_days is "0" and period_config is "", period type is yearly.  Next estimated time is 10 years out (good), but should the others be zero or null?
I can get this to work and this will save me a lot of effort from having to put REST sensors in for all future chores.

**Comment by isabellaalstrom** [comment]
Do you mean this fixes your problem or is there still an issue?

**Comment by GlennGoddard** [comment]
It fixed the issues, I just was not sure what the intent of the period_days was.
