### ISSUE TITLE
2025.11 Unable to install package pygrocy2

### ISSUE THREAD

**Issue by philhawthorne** [custom-components/grocy#358]
When running 2025.11 (beta) the following errors are in the Home Assistant log on startup

```
Unable to install package pygrocy2==2.4.1: × No solution found when resolving dependencies:
  ╰─▶ Because pygrocy2==2.4.1 depends on pydantic>=2.11.3,<2.12.dev0 and
      pydantic==2.12.2, we can conclude that pygrocy2==2.4.1 cannot be used.
      And because you require pygrocy2==2.4.1, we can conclude that your
      requirements are unsatisfiable.
Setup failed for custom integration 'grocy': Requirements for grocy not found: ['pygrocy2==2.4.1']
```

**Expected behavior**
Grocy component to be loaded

**To Reproduce**
1. Install 2025.11 beta
2. Run 2025.11 beta with Grocy custom component
3. Experience issue above

### General information to help debugging:
Home Assistant 2025.11 adds support for Python 3.14 which may be causing this.

**Comment by tetele** [comment]
Fixed upstream (in `pygrocy2`), awaiting release and new version number in order to bump dependencies in the custom component

**Comment by DeltaNu1142** [comment]
Experienced same issue, 2025.11 is now a production release.

**Comment by mattpeufpeuf** [comment]
Yes 2025.11, grocy can't loaded

**Comment by Kramer76** [comment]
I dont understand (novice)... I cant install the Grocy integration... Is there anything I can do to make it work?
I just get "something went wrong" when trying to install Grocy integration via Hacs in HA

**Comment by Wolve1** [comment]
Still not working for me with Home Assistant 2025.10.3.

So I need to update?

**Comment by nirvine** [comment]
I cannot add the integration either. 
I am using:
Installation method Home Assistant OS
Core 2025.11.1
Supervisor 2025.11.2
Operating System 16.3
Frontend 20251105.0

**Comment by patienttruth** [comment]
As a bandaid until the release is out, you can manually make the changes that were made here.

https://github.com/custom-components/grocy/pull/359

Thank you for this @tetele !

**Comment by helicalchris** [comment]
Any idea when the release will be out? I made the mistake of deleting the existing integration to reinstall it to try to fix the not loaded failure and then found this issue too late. It won't install now with failed config flow, I suspect it's the same underlying issue? 
Before I try to piece together why it's not working, just wondering if I should be waiting for this release so I can try the automated install first

**Comment by davidr521** [comment]
> Any idea when the release will be out? I made the mistake of deleting the existing integration to reinstall it to try to fix the not loaded failure and then found this issue too late. It won't install now with failed config flow, I suspect it's the same underlying issue? Before I try to piece together why it's not working, just wondering if I should be waiting for this release so I can try the automated install first

^^This. Would love not to have to do anything manually.

Any update/ETA?

**Comment by iamkarlson** [comment]
Hey guys, I forked this repo and published to HACS here https://github.com/iamkarlson/grocy

There's a lot of issues have been fixed including migrating to the latest HA.

**Comment by patienttruth** [comment]
@iamkarlson that looks great. Are there any issues I should anticipate in migrating, or should it just drop in? e.g. can I just uninstall the current version and re-install with the fork and will it pick up the configuration? Thanks for sharing this!

**Comment by iamkarlson** [comment]
I haven't tested such case yet. this grocy repo is quite outdated and I haven't used it for a while. when I forked it, I migrated my HA with no issues by indeed reinstalling it. Perhaps you may want to uninstall old repo first, restart HA, ensure that you automations on grocy entities are broken (it means they are indeed deleted), install a new one, and again restart. 

But there's no naming changes in new versions so all functionality should be working as it is. at least everything before I released a bunch of PRs that were pending and a few totally new. I know how painful it can be when your very used part of smarthome breaks but i would say byte a bullet and migrate even if there're issues. If you need help or there's a bug - create an issue in my fork, i will try helping you.

Also, I'm not sure if I would have time for that in foreseeable future, but my intention is to move this integration to Home Assistant core. One of the benefits is this would make possible to automatically enable integration by a discovery request from the official grocy ~~addon~~ app.
Another thing, grocy ui is ugly and i want to have a complete feature parity of the integration with UI so I don't need to use it.


this is just an indication of the direction where I want to develop this project. for whoever land in this issue with questions about either you should migrate or not.
